model:
  name: "storesnet18"
  ck_dir: "./checkpoints/storesnet18" 
  n_components: 2
  stochastic: 1

experiment:
  name: "test storesnet18"
  seed: 42
  res_dir: "./results/storesnet18"

params:
  n_epochs: [200]
  batch_size: 512
  ece_bins: 15
  
dataset:
  name: "CIFAR10"
  dir_clean: ./data/CIFAR10
  dir_corrupted: ./data/CIFAR10-C
  in_channel: 3
  n_classes: 10
  download: False