model:
  name: "storesnet18"
  ck_dir: "./checkpoints/storesnet18" 
  n_components: 2
  stochastic: 1

experiment:
  name: "test storesnet18"
  seed: 42
<<<<<<< HEAD
  res_dir: "./results/storesnet18"

params:
  n_epochs: [200]
  batch_size: 512

dataset:
  name: "CIFAR10"
  dir_clean: ./data/CIFAR10
  dir_corrupted: ./data/CIFAR10-C
  in_channel: 3
=======
  log_dir: "./runs/test"

params:
  n_epochs: [10, 20, 30, 40, 60, 80, 100, 140, 180, 200]
  batch_size: 512
  corrupted: False

dataset:
  dir_clean: ./data/FashionMNIST
  dir_corrupted: ./data/FashionMNIST-c
  in_channel: 1
>>>>>>> origin/main
  n_classes: 10
  download: False