model:
  name: "storesnet18"
  ck_dir: "./checkpoints/storesnet18" 
  n_components: 4
  stochastic: 2
  version: 2

experiment:
  name: "test storesnet18 version 2: without sampling during inference"
  seed: 42
  res_dir: "./results/storesnet18"

params:
  n_epochs: [20, 100, 200]
  batch_size: 512
  ece_bins: 20
  
dataset:
  name: "CIFAR10"
  dir_clean: ./data/CIFAR10
  dir_corrupted: ./data/CIFAR10-C
  in_channel: 3
  n_classes: 10
  corrupt_types: ['saturate', 'shot_noise', 'gaussian_noise', 'zoom_blur', 'glass_blur', 'brightness', 'contrast', 'motion_blur', 'pixelate', 'snow', 'speckle_noise', 'spatter', 'gaussian_blur', 'frost', 'defocus_blur',
                        'elastic_transform', 'impulse_noise', 'jpeg_compression', 'fog']