model:
  name: "storesnet18"
  ck_dir: "./checkpoints/storesnet18" 
  stochastic: 1
  n_component: 4

experiment:
  name: "train storesnet18"
  seed: 42
  log_dir: ".../runs/train"

params:
  n_epoch: 200
  batch_size: 128
  lr: 0.001
  aug_type: "geometric"
  milestones: [0.5, 0.9]
  final_factor: 0.3
  weight_decay: 0.
  entropy_weight: 0.4
  n_sample: 1
  kl_min: 0.05
  kl_max: 1
  prior_mean: 0.8
  prior_std: 0.64
  post_mean_init: [1.0, 0.25]
  post_std_init: [0.64, 0.50]

dataset:
  name: CIFAR10
  dir: ./data/CIFAR10
  in_channel: 3
  n_classes: 10