model:
  name: "resnet18"
  ck_dir: "./checkpoints/resnet18_v1" 

experiment:
  name: "train resnet18 with bnn augmented dataset, version 1: with data augmentation"
  seed: 42
  log_dir: ".../runs"

params:
  n_epoch: 300
  batch_size: 128
  lr: 1e-3
  aug_type: "geometric"
  weight_decay: 1e-4

dataset:
  name: CIFAR10-bnnaug
  dir: ./data/CIFAR10-aug
  in_channel: 3
  n_classes: 10