bnn:
  name: "storesnet18"
  ck_dir: "./checkpoints/storesnet18"
  epoch: 300
  n_components: 4
  n_samples: 4

unet:
  ck_dir: "./checkpoints/layer"

experiment:
  name: "training unet with different intermediate layer groups"
  seed: 42
  log_dir: ".../logs"

loss:
  input_weight_initial: 0.5
  input_weight_final: 0.1
  betas: [0.5, 1.0, 1.5]

params:
  n_epochs: 100
  batch_size: 128
  lr: 1e-2
  weight_decay: 1e-5

dataset:
  name: CIFAR10
  dir: ./data/CIFAR10
  in_channels: 3
  n_classes: 10

layer_groups:
  shallow_layer: [1, 2]
  deep_layer: [3, 4]
  mid_layers: [2, 3]
