unet:
  ck_dir: "./checkpoints/unet_v3"
  epoch: 40

experiment:
  name: "generate noise and make new dataset v3"
  seed: 42
  log_dir: "./runs/noise_generation"

params:
  batch_size: 512

dataset:
  name: CIFAR10
  input_dir: ./data/CIFAR10
  in_channels: 3
  n_classes: 10
  download: False
  save_dir: ./data/CIFAR10-aug_v3
  save_dir_noisy: ./data/CIFAR10-noisy_v3
