model:
  name: "storesnet18"
  ck_dir: "./checkpoints/storesnet18"
  epoch: 200 
  n_components: 2

experiment:
  name: "generate noise and make new dataset v1"
  seed: 42
  log_dir: "./runs/noise_generation"

params:
  anta: 0.5
  lr: 1e-2
  batch_size: 512
  num_iter: 100

dataset:
  name: CIFAR10
  input_dir: ./data/CIFAR10
  in_channel: 3
  n_classes: 10
  download: False
  save_dir: ./data/CIFAR10-aug_v1
