unet:
  ck_dir: "./checkpoints/unet"
  epoch: 50

experiment:
  name: "generate noise and make new dataset"
  seed: 42
  log_dir: "./runs/noise_generation"

params:
  batch_size: 512

dataset:
  name: CIFAR10
  input_dir: ./data/CIFAR10
  in_channels: 3
  n_classes: 10
  save_dir: ./data/CIFAR10-aug
