unet:
  ck_dir: "./checkpoints/unet"
  epoch: 20

experiment:
  name: "generate noise and make new dataset v2"
  seed: 42
  log_dir: "./runs/noise_generation"

params:
  batch_size: 512

dataset:
<<<<<<< HEAD
  name: CIFAR10
  input_dir: ./data/CIFAR10
  in_channels: 3
  n_classes: 10
  download: False
  save_dir: ./data/CIFAR10-aug_v2
  save_dir_noisy: ./data/CIFAR10-noisy_v2
=======
  name: FashionMNIST
  input_dir: ./data/FashionMNIST
  in_channels: 1
  n_classes: 10
  download: False
  save_dir: ./data/FashionMNIST-aug_v2
  save_dir_noisy: ./data/FashionMNIST-noisy_v2
>>>>>>> origin/main
