model:
  name: "resnet18"
  ck_dir: "./checkpoints/resnet18_v2" 

experiment:
  name: "train resnet18 with bnn augmented dataset"
  seed: 42
  log_dir: ".../runs/train"

params:
  n_epoch: 200
  batch_size: 128
  lr: 1e-3
  geo_aug: True
  weight_decay: 1e-3

dataset:
  name: FashionMNIST-bnnaug
  dir: ./data/FashionMNIST-aug_v2
  in_channel: 1
  n_classes: 10
  download: False