model:
  name: "resnet18"
  ck_dir: "./checkpoints/resnet18_v3" 
  version: 3

experiment:
  name: "test resnet18 (version 3) on data augmentation + bnn augmentation"
  seed: 42
  res_dir: "./results"

params:
  n_epoch: [300]
  batch_size: 1024
  ece_bins: 20
  
dataset:
  name: CIFAR10
  dir_clean: ./data/CIFAR10
  dir_corrupted: ./data/CIFAR10-C
  in_channel: 3
  n_classes: 10
  # corrupt_types: ['saturate', 'shot_noise', 'gaussian_noise', 'zoom_blur', 'glass_blur', 'brightness', 'contrast', 'motion_blur', 'pixelate', 'snow', 'speckle_noise', 'spatter', 'gaussian_blur', 'frost', 'defocus_blur',
  #                 'elastic_transform', 'impulse_noise', 'jpeg_compression', 'fog']
  corrupt_types: ['saturate', 'shot_noise', 'zoom_blur', 'glass_blur', 'brightness', 'contrast', 'motion_blur', 'pixelate', 'snow', 'speckle_noise', 'spatter', 'frost', 'defocus_blur',
                  'elastic_transform', 'impulse_noise', 'jpeg_compression', 'fog']