model:
  name: "resnet18"
  ck_dir: "./checkpoints/resnet18_v0" 
  version: 0

experiment:
  name: "benchmark"
  seed: 42
  res_dir: "./results/resnet18_v0"

params:
  n_epoch: [20, 100, 200]
  batch_size: 512
  ece_bins: 20
  
dataset:
  name: CIFAR10
  dir_clean: ./data/CIFAR10
  dir_corrupted: ./data/CIFAR10-C
  in_channel: 3
  n_classes: 10