model:
  name: "resnet18"
  ck_dir: "./checkpoints/resnet18_v1" 
  version: 1

experiment:
  name: "test resnet18 (version 1), with data augmentation"
  seed: 42
  res_dir: "./results/resnet18_v1"

params:
  n_epoch: [20, 100, 200]
  batch_size: 512
  ece_bins: 20

dataset:
  name: CIFAR10
  dir_clean: ./data/CIFAR10
  dir_corrupted: ./data/CIFAR10-C
  in_channel: 3
  n_classes: 10
  corrupt_types: ['saturate', 'zoom_blur', 'glass_blur', 'brightness', 'contrast', 'motion_blur', 'pixelate', 'snow', 'speckle_noise', 'spatter', 'gaussian_blur', 'frost', 'defocus_blur',
                        'elastic_transform', 'impulse_noise', 'jpeg_compression', 'fog']