model:
  name: "resnet18"
  ck_dir: "./checkpoints/resnet18_v2" 
  version: 0

experiment:
  name: "test resnet18 clean and corrupted dataset"
  seed: 42
  res_dir: "./results/resnet18_v2"

params:
  n_epoch: [200]
  batch_size: 512

dataset:
  name: CIFAR10
  dir_clean: ./data/CIFAR10
  dir_corrupted: ./data/CIFAR10-C
  in_channel: 3
  n_classes: 10
  download: False