model:
  name: "resnet18"
<<<<<<< HEAD
  ck_dir: "./checkpoints/resnet18_v0" 
  version: 0

experiment:
  name: "test resnet18 clean and corrupted dataset"
  seed: 42
  res_dir: "./results/resnet18_v0"

params:
  n_epoch: [200]
  batch_size: 512

dataset:
  name: CIFAR10
  dir_clean: ./data/CIFAR10
  dir_corrupted: ./data/CIFAR10-C
  in_channel: 3
=======
  ck_dir: "./checkpoints/resnet18_v2" 

experiment:
  name: "test resnet18 with bnnaug on only bnn-aug_v2 dataset"
  seed: 42
  log_dir: "./logs/test"

params:
  n_epoch: [20, 50, 60, 100, 120, 150, 170, 200]
  batch_size: 512

dataset:
  dir_clean: ./data/FashionMNIST
  dir_corrupted: ./data/FashionMNIST-c
  in_channel: 1
>>>>>>> origin/main
  n_classes: 10
  download: False