model:
  name: "resnet18"
  ck_dir: "./checkpoints/resnet18_v0" 

experiment:
  name: "benchmark"
  seed: 42
  log_dir: ".../logs"

params:
  n_epoch: 200
  batch_size: 128
  lr: 1e-3
  aug_type: "geometric"
  weight_decay: 1e-3

dataset:
  name: CIFAR10
  dir: ./data/CIFAR10
  in_channel: 3
  n_classes: 10