model:
  name: "resnet18"
  ck_dir: "./checkpoints/resnet18_v2" 

experiment:
  name: "train resnet18 (version 2) with gaussian data augmentation"
  seed: 42
  log_dir: ".../runs"

params:
  n_epoch: 300
  batch_size: 128
  lr: 1e-3
  weight_decay: 1e-4
  aug_type: "gaussian"

dataset:
  name: CIFAR10
  dir: ./data/CIFAR10
  in_channel: 3
  n_classes: 10