bnn:
  name: "storesnet18"
  ck_dir: "./checkpoints/storesnet18"
  epoch: 80
  n_components: 4

unet:
  ck_dir: "./checkpoints/unet"

experiment:
  name: "train unet with perceptual loss for more versatile noise generation"
  seed: 42
  log_dir: ".../logs"

loss:
  input_weight_initial: 0.25
  input_weight_final: 0.1
  intermediate_layers: [4, 6, 8]
  beta: 1.5

params:
  n_epochs: 50
  batch_size: 128
  lr: 1e-2
  weight_decay: 5e-4  

dataset:
  name: CIFAR10
  dir: ./data/CIFAR10
  in_channels: 3
  n_classes: 10