bnn:
  name: "storesnet18"
  ck_dir: "./checkpoints/storesnet18"
  epoch: 200 
  n_components: 2

unet:
  ck_dir: "./checkpoints/unet_v3"

experiment:
  name: "train unet v2(perceptual loss) for noise generation"
  seed: 42
  log_dir: ".../logs"

perceptual:
  ck_dir: "./checkpoints/resnet18_v0"
  epoch: 100
  input_weight_initial: 1.
  input_weight_final: 0.3
  intermediate_weight: 0.025
  prediction_weight: 0.
  perceptual_layers: [2, 4, 6, 8]

params:
  n_epochs: 100
  batch_size: 128
  lr: 1e-2
  anta: 0.5
  weight_decay: 5e-4  

dataset:
  name: CIFAR10
  dir: ./data/CIFAR10
  in_channels: 3
  n_classes: 10
  download: False